Thunder/Models/User/Friend.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Data.Entity;
using System.Linq;
using System.Web;
using Thunder.Models.User;

namespace Thunder.Models
{
    public class Friend
    {
        [Key]
        public int Id { get; set; }

        public string UserID { get; set; }
        public string FriendUserId { get; set; }

        
    }



    public class FriendsDbContext : DbContext
    {
        public DbSet<Friend> Friends { get; set; }

        public FriendsDbContext() : base("DefaultConnection") { }
    }
}

Thunder/Models/User/FriendList.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Data.Entity;
using System.Linq;
using System.Web;

namespace Thunder.Models
{
    public class FriendList
    {
        [Key]
        public string UserId { get; set; }

        public List<string> Friend_UserIds {get;set;} //Lista med UserId
    }



    public class FriendListDbContext : DbContext
    {
        public DbSet<FriendList> Friends { get; set; }

        public FriendListDbContext() : base("DefaultConnection") { }
    }
}

Thunder/Models/User/FriendRequest.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Data.Entity;
using System.Linq;
using System.Web;

namespace Thunder.Models.User
{
    public class FriendRequest
    {
        [Key]
        public int Id { get; set; }
        public string RecieverId { get; set; }
        public string SenderId { get; set; }
    }

    public class FriendRequestDbContext : DbContext
    {
        public DbSet<FriendRequest> Requests { get; set; }

        public FriendRequestDbContext() : base("DefaultConnection") { }

    }
}

Thunder/Models/User/FriendRequests.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Data.Entity;
using System.Linq;
using System.Web;

namespace Thunder.Models.User
{
    public class FriendRequest
    {
        [Key]
        public int Id { get; set; }
        public string RecieverId { get; set; }
        public string SenderId { get; set; }
    }

    public class FriendRequestDbContext : DbContext
    {
        public DbSet<FriendRequest> Requests { get; set; }

        public FriendRequestDbContext() : base("DefaultConnection") { }

    }
}

Thunder/Models/User/Friends.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Data.Entity;
using System.Linq;
using System.Web;
using Thunder.Models.User;

namespace Thunder.Models
{
    public class Friends
    {
        [Key]
        public int Id { get; set; }

        public string UserID { get; set; }
        public string FriendUserId { get; set; }

        
    }



    public class FriendsDbContext : DbContext
    {
        public DbSet<Friends> Friends { get; set; }

        public FriendsDbContext() : base("DefaultConnection") { }
    }
}

Thunder/Models/User/Image.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Data.Entity;
using System.Linq;
using System.Web;

namespace Thunder.Models.User
{
    public class Image
    {   
       [Key]
        public string UserID { get; set; }
        [DisplayName("Bildtext (Frivilligt)")]
        public string Title { get; set; }
        [DisplayName("Ladda Upp Bild")]
        public string ImagePath { get; set; }
        [NotMapped]
        public HttpPostedFileBase ImageFile { get; set; }

    }

    public class ImageDbContext : DbContext
    {
        public DbSet<Image> Images { get; set; }

        public ImageDbContext() : base("DefaultConnection") { }
    }
}

Thunder/Models/User/Post.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Data.Entity;
using System.Linq;
using System.Web;
using Thunder.Models;

namespace Thunder.Models
{
    public class Post
    {
        [Key]
        public int Id { get; set; }

        public string UserId { get; set; } //Hör till en användares vägg
        public string Author_UserId { get; set; }
        public string Text { get; set; }

    }
}

public class PostDbContext : DbContext
{
    public DbSet<Post> Posts { get; set; }

    public PostDbContext() : base("DefaultConnection") { }
}

Thunder/Models/User/Profile.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Data.Entity;
using System.Linq;
using System.Web;
using Thunder.Models;
using Microsoft.AspNet.Identity;
using System.ComponentModel;

namespace Thunder.Models
{
    public class Profile
    {
        [Key]
        public string UserId { get; set; }

        [DisplayName("Förnamn")]
        public string FirstName { get; set; }

        [DisplayName("Efternamn")]
        public string LastName { get; set; }

        [DisplayName("Födelsedatum")]
        public DateTime BirthDate { get; set; }

        [DisplayName("Ort")]
        public string Location { get; set; }

        [DisplayName("Sysselsättning")]
        public string Occupation { get; set; }

        [DisplayName("Presentation")]
        public string Presentation { get; set; }

        //Används ej
        public HashSet<string> Interests { get; set; }


    }

        public class ProfileDbContext : DbContext
        {
            public DbSet<Profile> Profiles { get; set; }

            public ProfileDbContext() : base("DefaultConnection") { }
        }

    
}

Thunder/Controllers/FriendController.cs
using Microsoft.AspNet.Identity;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Thunder.Models;
using Thunder.Models.User;

namespace Thunder.Controllers
{
    public class FriendController : Controller
    {
        //Ta vort från vänförfrågning
        private void RemoveFromRequests(string userId, string friendUserId)
        {
            var ctx = new FriendRequestDbContext();
            var reqToRemove = ctx.Requests.
                SingleOrDefault(r => r.RecieverId == userId && r.SenderId == friendUserId);
            if (reqToRemove != null)
            {
                ctx.Requests.Remove(reqToRemove);
            }
            ctx.SaveChanges();
        }

        [HttpGet]
        public ActionResult SendFriendRequest(string userId)
        {
            if (userId != User.Identity.GetUserId())
            {
                var ctx = new FriendRequestDbContext();
                ctx.Requests.Add(new FriendRequest()
                {
                    SenderId = User.Identity.GetUserId(),
                    RecieverId = userId
                });
                ctx.SaveChanges();
            }

            return RedirectToAction("Index", "Home");
        }

        //Avböj vänförfrågan
        public ActionResult DenyFriendRequest(string userId)
        {
            var currentUserId = User.Identity.GetUserId();
            var ctx = new FriendRequestDbContext();
            var request = ctx.Requests.FirstOrDefault(r => r.RecieverId == currentUserId && r.SenderId == userId);
            if (request != null)
            {
                ctx.Requests.Remove(request);
                ctx.SaveChanges();
            }

            return Redirect(Request.UrlReferrer.ToString());
        }

        //Acceptera vänförfrågan
        public ActionResult AcceptFriendRequest(string userId)
        {
            var currentUserId = User.Identity.GetUserId();
            var ctx = new FriendsDbContext();
            var alreadyFriends = ctx.Friends.Any(u => u.UserID == currentUserId && u.FriendUserId == userId);
            if (!alreadyFriends)
            {
                ctx.Friends.Add(new Friend()
                {
                    UserID = currentUserId,
                    FriendUserId = userId
                });
                ctx.Friends.Add(new Friend()
                {
                    FriendUserId = currentUserId,
                    UserID = userId
                });
                RemoveFromRequests(currentUserId, userId);
                ctx.SaveChanges();
            }
            return Redirect(Request.UrlReferrer.ToString());
        }

        //Ta bort vän
        public ActionResult RemoveFriend(string userId)
        {
            var currentUserId = User.Identity.GetUserId();
            var ctx = new FriendsDbContext();
            var friendRelationToremove = ctx.Friends.Where(p =>
                ((p.FriendUserId == userId) && (p.UserID == currentUserId)) ||
                ((p.FriendUserId == currentUserId) && (p.UserID == userId))).ToList();

            ctx.Friends.RemoveRange(friendRelationToremove);
            ctx.SaveChanges();
            return RedirectToAction("ViewProfile", "User");
        }
    }
}

Thunder/Controllers/ImageController.cs
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.UI.WebControls;
using Thunder.Models.User;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.EntityFramework;
using Image = Thunder.Models.User.Image;

namespace Thunder.Controllers
{
    [Authorize]
    public class ImageController : Controller
    {
        [HttpGet]
        public ActionResult AddImage()
        {
            return View();
        }

        //Tar in en image model och ger bilden ett unikt namn i databasen och sparar filsökvägen.
        [HttpPost]
        public ActionResult Add(Thunder.Models.User.Image imageModel)
        {
            string fileName = Path.GetFileNameWithoutExtension(imageModel.ImageFile.FileName);
            string extension = Path.GetExtension(imageModel.ImageFile.FileName);
            fileName = fileName + DateTime.Now.ToString("yymmssfff") + extension;
            imageModel.ImagePath = "~/Image/" + fileName;
            fileName = Path.Combine(Server.MapPath("~/Image/"), fileName);
            imageModel.ImageFile.SaveAs(fileName);
            imageModel.UserID = User.Identity.GetUserId();


            ImageDbContext ctx = new ImageDbContext();
            var existingImage = ctx.Images.FirstOrDefault(u => u.UserID == imageModel.UserID);
            if(existingImage != null)
            {
                ctx.Images.Remove(existingImage);
            }
            ctx.Images.Add(imageModel);
            ctx.SaveChanges();
            
           

            ModelState.Clear();

            return RedirectToAction("EditProfile", "User");
        }

        [HttpGet]
        public ActionResult ViewImage(Image imageModel)
        {
            return View(imageModel);
        }
        
    }
}

Thunder/Controllers/UserController.cs
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.EntityFramework;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Thunder.Models;
using Thunder.Models.User;
using Thunder.Models.ViewModel;

namespace Thunder.Controllers
{
    [Authorize] //Alla vyer i denna kontroller kräver inlogg
    public class UserController : Controller
    {
        //Skapar en viewmodel för visning av profilsidan
        private ProfileViewModel GetProfileViewModel(string userId)
        {
            var profileCtx = new ProfileDbContext();
            var friendCtx = new FriendsDbContext();
            var postCtx = new PostDbContext();
            var ImgCtx = new ImageDbContext();

            var image = ImgCtx.Images.FirstOrDefault(u => u.UserID == userId);

            var profile = profileCtx.Profiles.FirstOrDefault(p => p.UserId == userId);
            if (profile.Interests == null)
            {
                profile.Interests = new HashSet<string>();
            }

            var posts = postCtx.Posts.Where(po => po.UserId == userId).ToList();
            var friends = friendCtx.Friends.Where(f => f.UserID == userId).ToList();
            var friendList = new List<FriendViewModel>();

            if (friends != null)
            {
                foreach (var f in friends)
                {
                    var friendProfile = profileCtx.Profiles.SingleOrDefault(p => p.UserId == f.FriendUserId);
                    friendList.Add(FriendViewModel.FromProfile(friendProfile));
                }
            }

            return new ProfileViewModel()
            {
                Profile = profile,
                Friends = friendList,
                Posts = posts,
                Image = image
            };
        }


        // GET: User
        public ActionResult Index()
        {
            return RedirectToAction("ViewProfile");
        }

        //
        public ActionResult EditProfile()
        {
            var ctx = new ProfileDbContext();
            var userId = User.Identity.GetUserId();
            var profileViewModel = GetProfileViewModel(userId);

            return View(profileViewModel);
        }

        //Ändra profil
        [HttpPost]
        public ActionResult EditProfile(ProfileViewModel p)
        {
            var ctx = new ProfileDbContext();
            var userId = User.Identity.GetUserId();
            var profile = ctx.Profiles.FirstOrDefault(pr => pr.UserId == userId);
            profile.Location = p.Profile.Location;
            profile.Occupation = p.Profile.Occupation;
            profile.Presentation = p.Profile.Presentation;
            ctx.SaveChanges();

            return RedirectToAction("ViewProfile");
        }

        //Visa profilsida
        public ActionResult ViewProfile(string userId)
        {
            if (string.IsNullOrEmpty(userId))
            {
                userId = User.Identity.GetUserId();
            }
            var profileViewModel = GetProfileViewModel(userId);
            return View(profileViewModel);
        }

        //Returnerar partial View med alla posts som hör till en användares profilsida
        public ActionResult _DisplayPostsPartial(string userId)
        {
            var posts = new PostDbContext().Posts.Where(p => p.UserId == userId).OrderByDescending(p=> p.Id).ToList();
            var authors = new ProfileDbContext().Profiles.ToList();
            var postList = new List<PostViewModel>();

            foreach (var p in posts)
            {
                var author = authors.FirstOrDefault(a => a.UserId == p.Author_UserId);

                postList.Add(new PostViewModel()
                {
                    Author_UserId = p.Author_UserId,
                    Author_FullName = string.Concat(author.FirstName, " ", author.LastName),
                    Text = p.Text,
                    UserId = p.UserId
                });
            }
            return PartialView(postList);
        }
    }
}

Thunder/Views/User/EditProfile.cshtml
@model Thunder.Models.ProfileViewModel

@{
    ViewBag.Title = "EditProfile";
}

<h2>Din personliga information</h2>

<div class="container">
    <div class="row">
        <div class="col-lg-4">
            <img class="img-thumbnail" src="@Url.Content(Model.Image.ImagePath)" />
            @Html.ActionLink("Byt Profilbild", "AddImage", "Image",
              new { userId = Model.Profile.UserId } ,new {@class = "btn btn-default" })
        </div>
    </div>
    <div class="row">
        @Html.ActionLink("Ändra lösenord", "Index", "Manage",
            new { userId = Model.Profile.UserId } ,new {@class = "btn btn-default" })
        @using (Html.BeginForm("EditProfile", "User", FormMethod.Post, new { @class = "form-horizontal", role = "form" }))
        {
            @Html.AntiForgeryToken()

            <div class="form-horizontal">
                <h4>Beskriv dig själv!</h4>
                <hr />

                @Html.ValidationSummary(true, "", new { @class = "text-danger" })

                <div class="form-group">
                    @Html.LabelFor(model => model.Profile.Presentation, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.TextAreaFor(model => model.Profile.Presentation, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Profile.Presentation, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.Profile.Location, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.Profile.Location, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Profile.Location, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.Profile.Occupation, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.Profile.Occupation, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Profile.Occupation, "", new { @class = "text-danger" })
                    </div>
                </div>
                <div class="form-group">
                    <input type="submit" value="Spara" class="btn btn-default" />
                </div>
            </div>
        }
    </div>



    <div>
        @Html.ActionLink("Tillbaka till profilsida", "Index")
    </div>
</div>
@section Scripts {

    @Scripts.Render("~/bundles/jqueryval")

}

Thunder/Views/User/ViewProfile.cshtml
@using Thunder.Models
@using Microsoft.AspNet.Identity
@model ProfileViewModel
@{
    var profileData = Model.Profile;
    List<Post> posts = Model.Posts;
    var friends = Model.Friends;
    var fullName = string.Concat(profileData.FirstName, " ", profileData.LastName);
    var age = DateTime.Now.Year - profileData.BirthDate.Year;
    var isCurrentUser = (User.Identity.GetUserId() == profileData.UserId);
    var alreadyFriends = friends.Any(f => f.UserId == User.Identity.GetUserId());
}
<h2 id="testRubrik">Profilsida för @fullName</h2>
<div class="container-fluid">

    <div class="row">
        <div class="col-lg-4">
            <div class="row">
                @if (Model.Image != null)
                {
                    <img src="@Url.Content(Model.Image.ImagePath)" class="img-thumbnail" alt="profilbild">
                }
            </div>
            <div class="row">
                <b>@fullName</b> - @age år<br />
                <!-- Button trigger modal -->
                <button type="button" class="btn btn-default" data-toggle="modal" data-target="#showFriendsModal">
                    Vänner <span class="badge">@friends.Count</span>
                </button>
                @if (!isCurrentUser && !alreadyFriends)
                {
                    @Html.ActionLink("Lägg till vän", "SendFriendRequest", "Friend",
                         new { userId = profileData.UserId },
                         new { @class = "btn btn-default" })
                }
                else
                {
                    if (!isCurrentUser)
                    {
                        <span class="btn btn-success">Ni är vänner <span class="glyphicon glyphicon-heart"></span></span>
                    }
                    else
                    {
                        @Html.ActionLink("Ändra din profil", "EditProfile", "User", null,
                                                 new { @class = "btn btn-default" })
                    }
                }
                <br />
                <ul class=list-unstyled>
                    <li>
                        <b>Ort: </b>@profileData.Location
                    </li>
                    <li>
                        <b>Sysslar med:</b> @profileData.Occupation
                    </li>
                </ul>

            </div>
        </div>
        <div class="col-lg-8">
            <div class="row">
                <h4>Presentation</h4>
                <p>@profileData.Presentation</p>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-lg-offset-4">
            @if (!isCurrentUser && alreadyFriends)
            {
                Html.RenderPartial("_NewPostPartial", Model);
            }
            else if(!isCurrentUser && !alreadyFriends)
            {
                <h4 class="text-danger">Skicka en vänförfrågan för att kunna skriva till @profileData.FirstName!</h4>
            }
        </div>
    </div>

    <div class="row">
        <div class="col-lg-offset-4">
            <h4>@string.Concat(Model.Profile.FirstName, "s") vägg:</h4>
            @{Html.RenderAction("_DisplayPostsPartial", "User",
                                                        new { userId = Model.Profile.UserId });}
        </div>
    </div>
</div>
    <!-- Modal: Visar alla vänner vid klick på vänner-knappen -->
    <div class="modal fade" id="showFriendsModal" tabindex="-1" role="dialog" aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title">Vänner</h5>
                </div>
                <div class="modal-body">
                    @{ if (friends.Count == 0)
                        {
                            <p>Här var det tomt...</p>
                        }
                        else
                        {
                            <table class="table">
                                <thead>
                                    <tr>
                                        <th scope="col">Namn</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    @foreach (var f in friends)
                                    {
                                        <tr>
                                            <td>
                                                @Html.ActionLink(f.FullName, "ViewProfile", "User",
                                                    new { userId = f.UserId }, null)
                                            </td>
                                            @if (isCurrentUser)
                                            {
                                                <td>
                                                    @Html.ActionLink(
                                                        "Ta bort vän",
                                                        "RemoveFriend",
                                                        "Friend",
                                                        new { userId = f.UserId },
                                                        new { @class = "btn btn-danger", id = "btnRemoveFriend" })
                                                </td>
                                            }

                                        </tr>
                                    }
                                </tbody>
                            </table>
                        }
                    }
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Stäng</button>
                </div>
            </div>
        </div>
    </div>


    @section scripts {

        <script language="javascript" type="text/javascript">
            $(document).ready(function () {

                $('#send-post-form').submit(function (ev) {
                    ev.preventDefault();

                    var data = {
                        Author_UserId: $('#author-id').val(),
                        UserId: $('#to-user-id').val(),
                        Text: $('#post-text').val().trim()
                    };

                    $.ajax({
                        url: '/api/wall/post/send',
                        type: 'POST',
                        data: data,
                        success: function (response) {
                            $('#postInfo').append('<p>' + response + '</p>');
                            $('#post-text').val('');
                            window.location.reload();
                        },
                        error: function (response) {
                            $('#postInfo').append('<p style="color:red">' + response + '</p>');
                            $('#post-text').val('');
                        }
                    });
                });
            });
        </script>
    }

Thunder/Views/User/_DisplayPostsPartial.cshtml
@model List<Thunder.Models.ViewModel.PostViewModel>


@if (Model.Count > 0)
{
    foreach (var p in Model)
    {
        <blockquote class="blockquote">
            <p>@p.Text</p>
            <footer>@Html.ActionLink(p.Author_FullName, "ViewProfile", 
                   new { userId = p.Author_UserId })</footer>
        </blockquote>
    }
}
else
{
    <p>Här var det tomt..</p>
}

Thunder/Views/User/_NewPostPartial.cshtml
@using Microsoft.AspNet.Identity
@model Thunder.Models.ProfileViewModel
<hr />
<div class="info" id="postInfo"></div>
<label class="text-info">Skriv ett inlägg till @Model.Profile.FirstName:</label>
<form id="send-post-form" class="form-inline">
    <input type="hidden" id="to-user-id" value="@Model.Profile.UserId" />
    <input type="hidden" id="author-id" value="@User.Identity.GetUserId()" />
        <div class="input-group">
            <textarea id="post-text" rows="5" class="form-control" style="resize:none;" required></textarea>
        </div>
        <div class="input-group" style="vertical-align:bottom">
            <button type="submit" class="btn btn-success">
                Skicka
            </button>
        </div>
</form>